In [100]:
import pandas as pd
from io import StringIO

data = """Customer_ID,Name,Age,Gender,Email,Signup_Date,Country,Purchase_Amount
C001, John Doe ,29,Male,john.doe@email.com,2023-01-15,USA,120.50
C002,Jane Smith, ,Female,janesmith@email.com,15/02/2023,United States,85
C003,Bob Lee,45,M,bob.lee@email,2023/03/01,US,3000
C004,Alice Brown,thirty,Female,alice.brown@email.com,2023-03-10,Canada,NaN
C005,Chris Green,22,Male,,03-25-2023,canada,45.75
C006,Emma White,27,Female,emma.white@email.com,2023-04-01,UK,60
C006,Emma White,27,Female,emma.white@email.com,2023-04-01,UK,60
C007,Tom Black,150,Male,tom.black@email.com,2023-04-15,U.K.,99999
C008,Sara Blue,31,Female,sara.blue@email.com,2023-05-05,India,70.00
C009, ,40,Female,unknown@email.com,2023-05-20,INDIA,55
C010,Mike Yellow,35,Male,mike.yellow@email.com,2023/06/01,USA,abc
"""

df = pd.read_csv(StringIO(data))
df

,Customer_ID,Name,Age,Gender,Email,Signup_Date,Country,Purchase_Amount
0,C001,John Doe,29,Male,john.doe@email.com,2023-01-15,USA,120.50
1,C002,Jane Smith,,Female,janesmith@email.com,15/02/2023,United States,85
2,C003,Bob Lee,45,M,bob.lee@email,2023/03/01,US,3000
3,C004,Alice Brown,thirty,Female,alice.brown@email.com,2023-03-10,Canada,NaN
4,C005,Chris Green,22,Male,NaN,03-25-2023,canada,45.75
5,C006,Emma White,27,Female,emma.white@email.com,2023-04-01,UK,60
6,C006,Emma White,27,Female,emma.white@email.com,2023-04-01,UK,60
7,C007,Tom Black,150,Male,tom.black@email.com,2023-04-15,U.K.,99999
8,C008,Sara Blue,31,Female,sara.blue@email.com,2023-05-05,India,70.00
9,C009,,40,Female,unknown@email.com,2023-05-20,INDIA,55
10,C010,Mike Yellow,35,Male,mike.yellow@email.com,2023/06/01,USA,abc

In [101]:
df.to_csv('raw_data.csv', index=False)
print("DataFrame 'raw_data.csv'")

DataFrame 'raw_data.csv'

In [102]:
df.head(10)

,Customer_ID,Name,Age,Gender,Email,Signup_Date,Country,Purchase_Amount
0,C001,John Doe,29,Male,john.doe@email.com,2023-01-15,USA,120.50
1,C002,Jane Smith,,Female,janesmith@email.com,15/02/2023,United States,85
2,C003,Bob Lee,45,M,bob.lee@email,2023/03/01,US,3000
3,C004,Alice Brown,thirty,Female,alice.brown@email.com,2023-03-10,Canada,NaN
4,C005,Chris Green,22,Male,NaN,03-25-2023,canada,45.75
5,C006,Emma White,27,Female,emma.white@email.com,2023-04-01,UK,60
6,C006,Emma White,27,Female,emma.white@email.com,2023-04-01,UK,60
7,C007,Tom Black,150,Male,tom.black@email.com,2023-04-15,U.K.,99999
8,C008,Sara Blue,31,Female,sara.blue@email.com,2023-05-05,India,70.00
9,C009,,40,Female,unknown@email.com,2023-05-20,INDIA,55

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      11 non-null     object
 1   Name             11 non-null     object
 2   Age              11 non-null     object
 3   Gender           11 non-null     object
 4   Email            10 non-null     object
 5   Signup_Date      11 non-null     object
 6   Country          11 non-null     object
 7   Purchase_Amount  10 non-null     object
dtypes: object(8)
memory usage: 836.0+ bytes

In [104]:
df.describe(include='all')

,Customer_ID,Name,Age,Gender,Email,Signup_Date,Country,Purchase_Amount
count,11,11,11,11,10,11,11,10
unique,10,10,10,3,9,10,9,9
top,C006,Emma White,27,Female,emma.white@email.com,2023-04-01,USA,60
freq,2,2,2,6,2,2,2,2

In [105]:
df.isnull().sum()

Customer_ID        0
Name               0
Age                0
Gender             0
Email              1
Signup_Date        0
Country            0
Purchase_Amount    1
dtype: int64

In [106]:
df.duplicated().sum()

np.int64(1)

In [107]:
df = df.drop_duplicates()

In [108]:
df['Country'].unique()

array(['USA', 'United States', 'US', 'Canada', 'canada', 'UK', 'U.K.',
       'India', 'INDIA'], dtype=object)

In [109]:

df['Gender'].unique()

array(['Male', 'Female', 'M'], dtype=object)

In [110]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

/tmp/ipython-input-1391001171.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

In [111]:
df['Purchase_Amount'] = pd.to_numeric(df['Purchase_Amount'], errors='coerce')

/tmp/ipython-input-92011620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Purchase_Amount'] = pd.to_numeric(df['Purchase_Amount'], errors='coerce')

In [112]:
df

,Customer_ID,Name,Age,Gender,Email,Signup_Date,Country,Purchase_Amount
0,C001,John Doe,29.0,Male,john.doe@email.com,2023-01-15,USA,120.50
1,C002,Jane Smith,NaN,Female,janesmith@email.com,15/02/2023,United States,85.00
2,C003,Bob Lee,45.0,M,bob.lee@email,2023/03/01,US,3000.00
3,C004,Alice Brown,NaN,Female,alice.brown@email.com,2023-03-10,Canada,NaN
4,C005,Chris Green,22.0,Male,NaN,03-25-2023,canada,45.75
5,C006,Emma White,27.0,Female,emma.white@email.com,2023-04-01,UK,60.00
7,C007,Tom Black,150.0,Male,tom.black@email.com,2023-04-15,U.K.,99999.00
8,C008,Sara Blue,31.0,Female,sara.blue@email.com,2023-05-05,India,70.00
9,C009,,40.0,Female,unknown@email.com,2023-05-20,INDIA,55.00
10,C010,Mike Yellow,35.0,Male,mike.yellow@email.com,2023/06/01,USA,NaN

In [113]:
df['Gender'] = df['Gender'].str.strip().str.lower()

/tmp/ipython-input-3122894814.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].str.strip().str.lower()

In [114]:

df['Gender'] = df['Gender'].replace({
    'm': 'Male',
    'male': 'Male',
    'female': 'Female',
    'f': 'Female'
})

/tmp/ipython-input-4228748915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].replace({

In [115]:
df['Country'] = df['Country'].str.strip().str.lower()

df['Country'] = df['Country'].replace({
    'usa': 'USA',
    'us': 'USA',
    'united states': 'USA',
    'u.k.': 'UK',
    'uk': 'UK',
    'india': 'India',
    'canada': 'Canada'
})

/tmp/ipython-input-4264576885.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'] = df['Country'].str.strip().str.lower()
/tmp/ipython-input-4264576885.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'] = df['Country'].replace({

In [116]:
#df['Signup_Date'] = pd.to_datetime(df['Signup_Date'],errors='coerce')

In [117]:
df['Signup_Date'] = pd.to_datetime(
    df['Signup_Date'],
    errors='coerce',
    infer_datetime_format=True,
    dayfirst=True
)

/tmp/ipython-input-2615925914.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['Signup_Date'] = pd.to_datetime(
/tmp/ipython-input-2615925914.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['Signup_Date'] = pd.to_datetime(
/tmp/ipython-input-2615925914.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Signup_Date'] = pd.to_datetime(

In [118]:
df['Signup_Date'] = df['Signup_Date'].fillna(df['Signup_Date'].median())

/tmp/ipython-input-4221270627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Signup_Date'] = df['Signup_Date'].fillna(df['Signup_Date'].median())

In [119]:
df['Signup_Date']

0    2023-01-15
1    2023-04-08
2    2023-04-08
3    2023-03-10
4    2023-04-08
5    2023-04-01
7    2023-04-15
8    2023-05-05
9    2023-05-20
10   2023-04-08
Name: Signup_Date, dtype: datetime64[ns]

In [120]:
df['Purchase_Amount']=df['Purchase_Amount'].fillna(df['Purchase_Amount'].median())

/tmp/ipython-input-3857814742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Purchase_Amount']=df['Purchase_Amount'].fillna(df['Purchase_Amount'].median())

In [121]:
df['Age']

0      29.0
1       NaN
2      45.0
3       NaN
4      22.0
5      27.0
7     150.0
8      31.0
9      40.0
10     35.0
Name: Age, dtype: float64

In [122]:
df.loc[(df['Age'] < 0) | (df['Age'] > 100), 'Age'] = None

In [123]:
df['Age'] = df['Age'].fillna(df['Age'].median())

/tmp/ipython-input-1553325268.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].fillna(df['Age'].median())

In [124]:
import re

email_pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

df['Email_Valid'] = df['Email'].apply(
    lambda x: bool(re.match(email_pattern, str(x))) if pd.notna(x) else False
)


df[df['Email_Valid'] == False][['Email']]

/tmp/ipython-input-804607238.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Email_Valid'] = df['Email'].apply(

           Email
2  bob.lee@email
4            NaN

In [125]:
df.loc[df['Email_Valid'] == False, 'Email'] = None

In [126]:
df['Email'] = df['Email'].fillna('unknown@email.com')

/tmp/ipython-input-2568464868.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Email'] = df['Email'].fillna('unknown@email.com')

In [127]:
df

,Customer_ID,Name,Age,Gender,Email,Signup_Date,Country,Purchase_Amount,Email_Valid
0,C001,John Doe,29.0,Male,john.doe@email.com,2023-01-15,USA,120.50,True
1,C002,Jane Smith,31.0,Female,janesmith@email.com,2023-04-08,USA,85.00,True
2,C003,Bob Lee,45.0,Male,unknown@email.com,2023-04-08,USA,3000.00,False
3,C004,Alice Brown,31.0,Female,alice.brown@email.com,2023-03-10,Canada,77.50,True
4,C005,Chris Green,22.0,Male,unknown@email.com,2023-04-08,Canada,45.75,False
5,C006,Emma White,27.0,Female,emma.white@email.com,2023-04-01,UK,60.00,True
7,C007,Tom Black,31.0,Male,tom.black@email.com,2023-04-15,UK,99999.00,True
8,C008,Sara Blue,31.0,Female,sara.blue@email.com,2023-05-05,India,70.00,True
9,C009,,40.0,Female,unknown@email.com,2023-05-20,India,55.00,True
10,C010,Mike Yellow,35.0,Male,mike.yellow@email.com,2023-04-08,USA,77.50,True

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 10
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      10 non-null     object
 1   Name             10 non-null     object
 2   Age              10 non-null     float64
 3   Gender           10 non-null     object
 4   Email            10 non-null     object
 5   Signup_Date      10 non-null     datetime64[ns]
 6   Country          10 non-null     object
 7   Purchase_Amount  10 non-null     float64
 8   Email_Valid      10 non-null     bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(5)
memory usage: 730.0+ bytes

In [129]:
df['Age'] = df['Age'].astype('Int64')

/tmp/ipython-input-1150615803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].astype('Int64')

In [130]:
df['Gender'] = df['Gender'].astype('category')
df['Country'] = df['Country'].astype('category')

/tmp/ipython-input-903227661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].astype('category')
/tmp/ipython-input-903227661.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'] = df['Country'].astype('category')

In [131]:
df

,Customer_ID,Name,Age,Gender,Email,Signup_Date,Country,Purchase_Amount,Email_Valid
0,C001,John Doe,29,Male,john.doe@email.com,2023-01-15,USA,120.50,True
1,C002,Jane Smith,31,Female,janesmith@email.com,2023-04-08,USA,85.00,True
2,C003,Bob Lee,45,Male,unknown@email.com,2023-04-08,USA,3000.00,False
3,C004,Alice Brown,31,Female,alice.brown@email.com,2023-03-10,Canada,77.50,True
4,C005,Chris Green,22,Male,unknown@email.com,2023-04-08,Canada,45.75,False
5,C006,Emma White,27,Female,emma.white@email.com,2023-04-01,UK,60.00,True
7,C007,Tom Black,31,Male,tom.black@email.com,2023-04-15,UK,99999.00,True
8,C008,Sara Blue,31,Female,sara.blue@email.com,2023-05-05,India,70.00,True
9,C009,,40,Female,unknown@email.com,2023-05-20,India,55.00,True
10,C010,Mike Yellow,35,Male,mike.yellow@email.com,2023-04-08,USA,77.50,True

In [132]:
df.to_csv('cleaned_customer_data.csv', index=False)
print("DataFrame 'cleaned_customer_data.csv'")

DataFrame 'cleaned_customer_data.csv'